name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-fronend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: sudo npm i yarn -g

      - name: Build
        run: |
          make init-frontend
          make frontend

      # - name: Build
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build
      #     dir: frontend

      # - name: Install dependencies
      #   run: cd frontend && npm install

      # - name: Build
      #   run: cd frontend && npm run build

      # - name: Prepare env
      #   run: cp frontend/.env.example.local frontend/.env

      - name: Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ansible
          playbook: deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: -u ec2-user
          inventory: tequila-train.com
