name: Build

on:
  pull_request:
    branches: [master]
    paths:
      - contracts/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Artifact cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            contracts -> target

      - name: Remove binaries from cache
        run: rm -vf contracts/target/wasm32-unknown-unknown/release/*.wasm

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          target: wasm32-unknown-unknown

      - name: Install binaryen
        run: |
          wget -c https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz -O - | tar -xz -C .
          sudo cp binaryen-version_110/bin/wasm-opt /usr/bin/

      - name: Check fmt
        run: make fmt

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test-contracts

      - name: Build
        run: make contracts
